---
abstract: "[One line description of module's purpose here]"
author:
  - 'Mithun Ayachit <mithun@cpan.org>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CASCM-Wrapper
provides:
  CASCM::Wrapper:
    file: lib/CASCM/Wrapper.pm
    version: 0.01
requires:
  Config::Tiny: 0
  File::Which: 0
  Test::More: 0
  perl: 5.006001
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=CASCM-Wrapper
  repository: http://github.com/mithun/perl-cascm-wrapper
version: 0.01
